module.exports = {
  project_directory: "<project-directory>",
  options: "[options]",
  specify_project: "Please specify the project directory:",
  example: "For example:",
  run: "Run",
  all_options: "to see all options.",
  pull_issue: "If you have any problems, do not hesitate to file an issue:",
  show_help: "output usage information",
  show_version: "output the version number",
  err_npm_name_prefix: "Could not create a project called",
  err_npm_name_suffix: "because of npm naming restrictions:",
  pick_paltform_type: "Select which platform your project run?",
  platform_pc: "Desktop(PC)",
  platform_mobile: "Mobile device",
  app_type_select: "Select app type:",
  app_type_mutiple: "Mutiple page app",
  app_type_single: "Single page app",
  use_native_scroll: "Whether disable native scrolling?",
  creating: "Creating...",
  fetch_repo: "fetching template...",
  success: "create success",
  failed: "create failed",
  start_dev: "Get started with the following commands",
  dep_install: "Installing dependencies...",
  dir: "The directory",
  dir_exist: "contains files that could conflict:",
  conflict: "Either try using a new directory name, or remove the files listed above.",
  use_tab_view: "Use tab view as default router view?"
};
