module.exports = {
  project_directory: "项目名称",
  options: "[参数]",
  specify_project: "请指定一个项目名称(不要使用中文):",
  example: "例子:",
  run: "输入命令",
  all_options: "查看所有选项.",
  pull_issue: "如果你发现什么bug或者有好的建议, 不要吝啬到这里说出你的意见:",
  show_help: "展示此帮助信息",
  show_version: "展示版本",
  err_npm_name_prefix: "项目名称不能为",
  err_npm_name_suffix: "不符合npm命名规范(不要使用汉字、大写或特殊符号):",
  pick_paltform_type: "请选择要创建的项目类型(适用平台):",
  platform_pc: "桌面项目(PC)",
  platform_mobile: "移动项目",
  app_type_select: "请选择移动app类型:",
  app_type_mutiple: "多页入口",
  app_type_single: "单页入口",
  disable_native_scroll: "是否禁用原生滚动?(如果你不知道为什么就别禁用)",
  creating: "创建中...",
  fetch_repo: "拉取模板中...",
  success: "创建成功",
  failed: "创建失败",
  start_dev: "执行以下命令开始愉快的开发吧",
  dep_install: "安装依赖中...",
  dir: "目录",
  dir_exist: "包含以下冲突文件:",
  conflict: "文件冲突(已存在), 删除以上文件或使用别的项目名",
  use_tab_view: "使用tabview作为路由展示?"
};
